### ISSUE TITLE
Setup Vagrantfile

### ISSUE THREAD

**Issue by makeapp007** [inventory-squad-f18/inventory#6]
**As a** developer
**I need** a way to work locally with Vagrant
**So that** I can be independent of Bluemix availability

**Assumptions:** 
* Use Vagrant and VirtualBox to build a local dev environment
* Python will be used for development

**Acceptance Criteria:**
```
When I issue git clone on the project
Add I change into the project folder
And I issue vagrant up
Then I should have a complete development environment on my workstation
```

**Comment by dhruvkwal** [comment]
@makeapp007 @meetparekh09 @lingy1028 Hey guys! I've created the VagrantFile as per professors instructions. It would be great if you could check and let me know if it works fine and if there's anything else to add.

**Comment by makeapp007** [comment]
Two questions:

1. https://github.com/inventory-squad-f18/inventory/blob/VagrantFile/Vagrantfile?1538487947474&1538488078563#L17 Will this setting allow public access? Can I visit this website from 192.168.33.10? I think you need to remove host_ip: "127.0.0.1"

1. Do we need to install redis? What is this for?

**Comment by dhruvkwal** [comment]
@makeapp007 
1. Correct! I've updated it. 
2. Would we not need it for the database?

**Comment by meetparekh09** [comment]
Also, I think you should also commit `requirements.txt` file as when I issue `vagrant up` it gives me following error:

> default: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
